/* tslint:disable */
/* eslint-disable */
/**
 * Sample API
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetUsers200ResponseInner,
} from '../models/index';
import {
    GetUsers200ResponseInnerFromJSON,
    GetUsers200ResponseInnerToJSON,
} from '../models/index';

/**
 * 
 */
export class AppsFooApi extends runtime.BaseAPI {

    /**
     * Optional extended description in CommonMark or HTML.
     * Returns a list of users.
     */
    async getUsersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetUsers200ResponseInner>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/users`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetUsers200ResponseInnerFromJSON));
    }

    /**
     * Optional extended description in CommonMark or HTML.
     * Returns a list of users.
     */
    async getUsers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetUsers200ResponseInner>> {
        const response = await this.getUsersRaw(initOverrides);
        return await response.value();
    }

}
