/* tslint:disable */
/* eslint-disable */
/**
 * Sample API
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetUsers200ResponseInner
 */
export interface GetUsers200ResponseInner {
    /**
     * 
     * @type {number}
     * @memberof GetUsers200ResponseInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof GetUsers200ResponseInner
     */
    name?: string;
}

/**
 * Check if a given object implements the GetUsers200ResponseInner interface.
 */
export function instanceOfGetUsers200ResponseInner(value: object): value is GetUsers200ResponseInner {
    return true;
}

export function GetUsers200ResponseInnerFromJSON(json: any): GetUsers200ResponseInner {
    return GetUsers200ResponseInnerFromJSONTyped(json, false);
}

export function GetUsers200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUsers200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function GetUsers200ResponseInnerToJSON(value?: GetUsers200ResponseInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

